hmLoadTopic({
hmKeywords:"",
hmTitle:"Finance",
hmDescription:"Overview  DevMan’s financial management component, designed to complement or integrate to your accounting systems is crucial for effective management of diverse revenue streams.",
hmPrevLink:"documentmanagement.html",
hmNextLink:"income.html",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"<a href=\"devmanfunction.html\">DevMan functions<\/a>",
hmTitlePath:"DevMan functions > Finance",
hmHeader:"<p class=\"p_KidzHeader1New\"><span class=\"f_KidzHeader1New\">Finance<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzHeader12New\"><span class=\"f_KidzHeader12New\">Overview<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">DevMan’s financial management component, designed to complement or integrate to your accounting systems is crucial for effective management of diverse revenue streams.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">See the subsections below for business specific solutions available.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzHeader12New\"><span class=\"f_KidzHeader12New\">Topics<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_KidzNormalIndent\"><a href=\"income.html\" class=\"topiclink\" title=\"Money in - donations etc\">Income<\/a><\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_KidzNormalIndent\"><a href=\"accountingsystemintegration.html\" class=\"topiclink\" title=\"Transfer payments from DevMan\">Accounting system integration<\/a><\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_KidzNormalIndent\"><a href=\"expenditure.html\" class=\"topiclink\">Expenditure<\/a><\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
