pageinfo = [[1731306086,0,0,0,null],
	[1721644000,0,0,0,null],
	[1721644168,0,0,0,null],
	[1731305434,0,0,0,null],
	[1741000144,0,0,0,null],
	[1733908238,0,0,0,null],
	[1737716272,0,0,0,null],
	[1727866636,0,0,0,null],
	[1727866612,0,0,0,null],
	[1731418012,0,0,0,null],
	[1727866802,0,0,0,null],
	[1727866630,0,0,0,null],
	[1695125856,0,0,0,null],
	[1727866656,0,0,0,null],
	[1728903204,0,0,0,null],
	[1724410364,0,0,0,null],
	[1720438298,0,0,0,null],
	[1727866406,0,0,0,null],
	[1727866970,0,0,0,null],
	[1727866416,0,0,0,null],
	[1727866426,0,0,0,null],
	[1727866918,0,0,0,null],
	[1727866906,0,0,0,null],
	[1727866758,0,0,0,null],
	[1727866642,0,0,0,null],
	[1708426228,0,0,0,null],
	[1736751984,0,0,0,null],
	[1729154776,0,0,0,null],
	[1737032042,0,0,0,null],
	[1727866398,0,0,0,null],
	[1737533672,0,0,0,null],
	[1727866666,0,0,0,null],
	[1736521076,0,0,0,null],
	[1736515140,0,0,0,null],
	[1740734976,0,0,0,null],
	[1727866690,0,0,0,null],
	[1730901624,0,0,0,null],
	[1727866788,0,0,0,null],
	[1727866782,0,0,0,null],
	[1736753130,0,0,0,null],
	[1737362722,0,0,0,null],
	[1731500718,0,0,0,null]];
pagedata = [ ["./accountingsystemintegration.html","Accounting system integration","Overview  Reduce errors and increase productivity with a single point of entry. DevMan integrates to various finance and accounting systems, ...","./images/zoomimage.jpg"],
["./businessunits.html","Business units","Overview  DevMan allows you to set up all your business units for an organisation in an easy to see hierarchy using 4 levels. Your institutio...","./images/zoomimage.jpg"],
["./consent.html","Consent","Overview  Get your POPIA implementation plan off the ground, and painlessly achieve compliance by making practical use of the Consent module....","./images/zoomimage.jpg"],
["./debitorders.html","Debit orders","Overview  Drive efficiency, streamline the monthly administration of your debit order donors by using DevMan’s integration features.  To...","./images/zoomimage.jpg"],
["./devcommunication.html","Communication","Overview  Engage and build rapport with your audience via email and SMS channels. Take advantage of workflow automation to expand communicati...","./images/zoomimage.jpg"],
["./devcontact.html","Contacts","Overview  Create links between organisations and people with projects, approaches, interactions etc.  This provides a comprehensive, thr...","./images/zoomimage.jpg"],
["./devdashboard.html","Dashboards","Overview  Transform data sets into analytical snapshots. View crucial information at a glance. Dashboards are accessible on the top menus and...","./images/zoomimage.jpg"],
["./devfinance.html","Finance","Overview  DevMan’s financial management component, designed to complement or integrate to your accounting systems is crucial for effective ma...","./images/zoomimage.jpg"],
["./devmanfunction.html","DevMan functions","Working procedures","./images/zoomimage.jpg"],
["./devmanportal.html","DevMan portal","Overview  Simplify your tax-related tasks. Empower donors to effortlessly update their own tax details.  Topics  Features Add the p...","./images/zoomimage.jpg"],
["./devsecurity.html","Security","Overview  Computer security is an important component of a successful organisation. Avoid complacency, control access to activities and data ...","./images/zoomimage.jpg"],
["./documentmanagement.html","Document management","Overview  Reduce paper, and increase efficiency with the DevMan dossier (document) upload feature.  Topics  Features Upload documen...","./images/zoomimage.jpg"],
["./donationdepositprocess.html","Donation deposit process","Overview  Streamline the monthly administration and allocation of your donations received via direct bank deposit.  Topics  How it ...","./images/zoomimage.jpg"],
["./donations.html","Donations","Overview  Capture donations directly and if required, send a thank you letter to the donor.   Topics  Features Link donations to th...","./images/zoomimage.jpg"],
["./email.html","Email","Overview  Ensure your email campaigns are targeted and relevant, providing value to recipients to maintain their trust and engagement.  ...","./images/zoomimage.jpg"],
["./emailsetup.html","Email setup","Overview  Verify your email address and learn how to configure your sending domain.  Topics  Set up email The email address you wis...","./images/zoomimage.jpg"],
["./excelintegratedreports.html","Excel integrated reports","Overview  Effortlessly summarise, analyse and present data from DevMan directly to Excel for comprehensive reporting.  Topics  Feat...","./images/zoomimage.jpg"],
["./faq.html","Frequently asked questions","Overview  Browse through the FAQ for answers to the most common questions asked by DevMan users. Questions are organised by category with lin...","./images/zoomimage.jpg"],
["./faqcommunication.html","Communication","Topics  This section answers questions related to the different types of communications often asked by DevMan users. DevMan provides the appr...","./images/zoomimage.jpg"],
["./faqgeneral.html","General","Topics  Topics related to system requirements, browsers and internet access.  What are the DevMan system requirements? DevMan is a cost-...","./images/zoomimage.jpg"],
["./faqsearch.html","Find and search","Topics  Questions on surfacing information from finding a single record to basic and advanced search.  Search as you type Search Search ...","./images/zoomimage.jpg"],
["./faqsupport.html","Support","Overview  Assist us to investigate and resolve your requests and complaints or errors correctly and as quickly as possible.  Your clear,...","./images/zoomimage.jpg"],
["./gettingstarted.html","Getting started","Overview  Learn how DevMan works, understand the key concepts and background information. Pick up useful tips and tricks, identify the key ar...","./images/zoomimage.jpg"],
["./importsandupdates.html","Imports and updates","Overview  Easily apply a series of changes to a group of records by using the bulk update feature. Updates can be made to people, organisatio...","./images/zoomimage.jpg"],
["./income.html","Income","Overview  Accurate financial records are the lifeblood of your operation. Use the finance module complete with all supporting processes to se...","./images/zoomimage.jpg"],
["./index.html","Introduction","Introduction to Devman3","./images/zoomimage.jpg"],
["./linking.html","Linking","Link a person, organisation or project  Relationship links can be added and defined between people, organisations and projects.  These c...","./images/zoomimage.jpg"],
["./loggingin.html","Logging in","Overview  A strong login ensures that only authorised users gain access, preventing unauthorised access and potential breaches. Please see Se...","./images/zoomimage.jpg"],
["./mergecontacts.html","Merge contacts","Overview  If you have duplicate records of a person or organisation, these need to be merged to combine the history and linked records, such ...","./images/zoomimage.jpg"],
["./navigation.html","Navigation","Overview  To get started with DevMan, please view the step-by-step tutorials below. They outline the main elements you will encounter through...","./images/zoomimage.jpg"],
["./online-updates.html","Online updates","Overview  Contacts can review and update their own contact details directly in DevMan. DevMan provides two ways for contacts to safely update...","./images/zoomimage.jpg"],
["./onlinegiving.html","Online giving","Overview  Make giving effortless and simple with DevMan&#39;s integrated online giving portal. Offer donors a fast, easy and secure online giving...","./images/zoomimage.jpg"],
["./organisations.html","Organisations","Overview  Contact details and a profile of your donor, prospect or grantee organisation can be captured here. See how to capture, save and ed...","./images/zoomimage.jpg"],
["./people.html","People","Overview  This section will assist you to capture, save and edit your contacts&#39; details and profile. Links can be added to other profiles on ...","./images/zoomimage.jpg"],
["./quickguides.html","Product guides","Overview  We&#39;ve provided a number of guides explaining some of the more intricate features and processes on DevMan. These can be used for tra...","./images/zoomimage.jpg"],
["./sars.html","SARS","Overview  Achieve seamless tax compliance and donor data management.  Streamline s18A receipts and IT3(d) exports to SARS with our compr...","./images/zoomimage.jpg"],
["./sarsit3exports.html","SARS IT3 exports","Overview  Ensure accurate, efficient and compliant tax reporting. Use this feature to extract and export section 18A donor information as req...","./images/zoomimage.jpg"],
["./searching.html","Searching","Overview  Simple and advanced searching tools are available for most DevMan modules to assist with your reporting needs.  Topics  F...","./images/zoomimage.jpg"],
["./searchreport.html","Search &#38; report","Overview  DevMan&#39;s report and analytics platform provides rich search and reporting for all areas. Draw statistical high level summaries and ...","./images/zoomimage.jpg"],
["./section18areceipts.html","Section 18A receipts","Overview  Encourage donor giving by promptly providing any documentation they need for tax benefits available in their country.  Topics ...","./images/zoomimage.jpg"],
["./securityadvanced.html","Advanced","Overview  Secure your data, align DevMan user access with the security protocols in place at your organisation. These topics cover activities...","./images/zoomimage.jpg"],
["./whatsnew.html","What&#39;s new","New features in DevMan  Alumni integration Alumni integration has never been easier. We have streamlined the process for our existing integra...","./images/zoomimage.jpg"]];
