pageinfo = [[1695125864,0,0,0,null],
	[1705420174,0,0,0,null],
	[1695125652,0,0,0,null],
	[1708584016,0,0,0,null],
	[1710506916,0,0,0,null],
	[1718284450,0,0,0,null],
	[1705063984,0,0,0,null],
	[1710939218,0,0,0,null],
	[1696325746,0,0,0,null],
	[1716805338,0,0,0,null],
	[1695125734,0,0,0,null],
	[1714125382,0,0,0,null],
	[1695125766,0,0,0,null],
	[1696325850,0,0,0,null],
	[1695125846,0,0,0,null],
	[1717158682,0,0,0,null],
	[1717481200,0,0,0,null],
	[1695125788,0,0,0,null],
	[1717481248,0,0,0,null],
	[1718369710,0,0,0,null],
	[1716281542,0,0,0,null],
	[1701861800,0,0,0,null],
	[1695125798,0,0,0,null],
	[1695125856,0,0,0,null],
	[1695125832,0,0,0,null],
	[1696325822,0,0,0,null],
	[1696325814,0,0,0,null],
	[1710140908,0,0,0,null],
	[1705670934,0,0,0,null],
	[1695125664,0,0,0,null],
	[1720438298,0,0,0,null],
	[1717072206,0,0,0,null],
	[1705670508,0,0,0,null],
	[1717481786,0,0,0,null],
	[1656505248,0,0,0,null],
	[1707818046,0,0,0,null],
	[1696325696,0,0,0,null],
	[1696325664,0,0,0,null],
	[1656505248,0,0,0,null],
	[1696325804,0,0,0,null],
	[1717493482,0,0,0,null],
	[1696325780,0,0,0,null],
	[1695125950,0,0,0,null],
	[1716195126,0,0,0,null],
	[1708426228,0,0,0,null],
	[1696325840,0,0,0,null],
	[1717481386,0,0,0,null],
	[1707818458,0,0,0,null],
	[1708600682,0,0,0,null],
	[1696405280,0,0,0,null],
	[1717482008,0,0,0,null],
	[1718699018,0,0,0,null],
	[1695125778,0,0,0,null],
	[1715236298,0,0,0,null],
	[1695125840,0,0,0,null],
	[1696325762,0,0,0,null],
	[1695125726,0,0,0,null],
	[1713775758,0,0,0,null],
	[1705067676,0,0,0,null],
	[1708063948,0,0,0,null],
	[1696325788,0,0,0,null],
	[1696325830,0,0,0,null],
	[1696325752,0,0,0,null],
	[1718369838,0,0,0,null],
	[1716386782,0,0,0,null],
	[1718370274,0,0,0,null],
	[1721201116,0,0,0,null],
	[1718369776,0,0,0,null],
	[1715950124,0,0,0,null],
	[1701855826,0,0,0,null],
	[1709283412,0,0,0,null],
	[1708670202,0,0,0,null],
	[1718282962,0,0,0,null],
	[1695125492,0,0,0,null],
	[1696325768,0,0,0,null]];
pagedata = [ ["./accountingsystemintegration.html","Accounting system integration","Overview  Reduce errors and increase productivity with a single point of entry. DevMan integrates to various finance and accounting systems, ...","./images/zoomimage.jpg"],
["./actionsdue.html","Actions due","Overview  By setting up reminders, you can keep track of which activities are due and which have been completed. Letter reminders are set up ...","./images/zoomimage.jpg"],
["./activitiesinteraction.html","Activities / Interactions","Overview  As interactions are recorded on the system, you are notified in the Weekly activity section of the Home page: You may view these ne...","./images/zoomimage.jpg"],
["./aftertheevent.html","After the event","Overview  Enhance return on investment, engage with attendees and gather feedback via post-event surveys to drive improvement.  Topics &#38;...","./images/zoomimage.jpg"],
["./applicantsupport.html","Applicant support","Overview  If an applicant encounters difficulties when submitting their online application, check the topics below to see how you can assist....","./images/zoomimage.jpg"],
["./attheevent.html","At the event","Overview  Build their confidence and delight your attendees with a seamless online registration experience. Manage real-time event data on th...","./images/zoomimage.jpg"],
["./beforetheevent.html","Before the event","Overview  Plan the perfect event: kick off the planning process by addressing all components of the event. Stay on schedule and create clear ...","./images/zoomimage.jpg"],
["./budget.html","Budget","Overview  Align your budgets with expenditure, use this tool to load your budget before capturing any pledges or payments. Manage and review ...","./images/zoomimage.jpg"],
["./bursary-profile.html","Bursary profile","Overview  Initiate and solidify connections between students, sponsors and institutions. Provide comprehensive insight on key bursary data. &#38;...","./images/zoomimage.jpg"],
["./bursarymanagement.html","Bursary management","Overview  Transform your bursary management process with configurable, versatile workflow designed to streamline your tasks. Use the DevMan b...","./images/zoomimage.jpg"],
["./businessunits.html","Business units","Overview  DevMan allows you to set up all your business units for an organisation in an easy to see hierarchy using 4 levels. Your institutio...","./images/zoomimage.jpg"],
["./commitmentsbudget.html","Commitments","Overview  Improve spend forecasting accuracy and speed of data capture. This module is designed to streamline processing of recurring transac...","./images/zoomimage.jpg"],
["./consent.html","Consent","Overview  Get your POPIA implementation plan off the ground, and painlessly achieve compliance by making practical use of the Consent module....","./images/zoomimage.jpg"],
["./contract.html","Contracts","Overview  Use this feature to manage all your contracts.  Upload, store and organise your agreement records for easy access and retrieva...","./images/zoomimage.jpg"],
["./debitorders.html","Debit orders","Overview  Drive efficiency, streamline the monthly administration of your debit order donors by using DevMan’s integration features.  To...","./images/zoomimage.jpg"],
["./devcommunication.html","Communication","Overview  Engage and build rapport with your audience via email and SMS channels. Take advantage of workflow automation to expand communicati...","./images/zoomimage.jpg"],
["./devcontact.html","Contacts","Overview  Use this feature to manage all your contacts.  These may be linked to other contacts, organisations or projects.  Topics ...","./images/zoomimage.jpg"],
["./devdashboard.html","Dashboards","Overview  Transform data sets into analytical snapshots. View crucial information at a glance. Dashboards are accessible on the Home page, &#38;n...","./images/zoomimage.jpg"],
["./devfinance.html","Finance","Overview  DevMan’s financial management component, designed to complement or integrate to your accounting systems is crucial for effective ma...","./images/zoomimage.jpg"],
["./devmanfunction.html","DevMan functions","Working procedures","./images/zoomimage.jpg"],
["./devmanportal.html","DevMan portal","Overview  Simplify your tax-related tasks. Empower donors to effortlessly update their own tax details.  Topics  Features Add the p...","./images/zoomimage.jpg"],
["./devsecurity.html","Security","Overview  Computer security is an important component of a successful organisation. Avoid complacency, control access to activities and data ...","./images/zoomimage.jpg"],
["./documentmanagement.html","Document management","Overview  Reduce paper, and increase efficiency with the DevMan dossier (document) upload feature.  Topics  Features Upload documen...","./images/zoomimage.jpg"],
["./donationdepositprocess.html","Donation deposit process","Overview  Streamline the monthly administration and allocation of your donations received via direct bank deposit.  Topics  How it ...","./images/zoomimage.jpg"],
["./donations.html","Donations","Overview  Capture donations directly and if required, send a thank you letter to the donor.   Topics  Features Link donations to th...","./images/zoomimage.jpg"],
["./donorengagement.html","Donor engagement","Overview  Nurture relationships with donors to improve engagement and monitor the various prospect stages. Evaluate metrics by tracking inter...","./images/zoomimage.jpg"],
["./donorprofile.html","Donor profile","Overview  The starting point in your cultivation of lifelong relationships with both organisations and individuals. Empower your team with ac...","./images/zoomimage.jpg"],
["./email.html","Email","Overview  Ensure your email campaigns are targeted and relevant, providing value to recipients to maintain their trust and engagement.  ...","./images/zoomimage.jpg"],
["./emailsetup.html","Email setup","Overview  Verify your email address and learn how to configure your sending domain.  Topics  Set up email The email address you wis...","./images/zoomimage.jpg"],
["./eventmanagement.html","Event management","Overview  Create and manage memorable events, connect and engage with attendees to provide a more personalised experience. Use this module to...","./images/zoomimage.jpg"],
["./excelintegratedreports.html","Excel integrated reports","Overview  Effortlessly summarise, analyse and present data from DevMan directly to Excel for comprehensive reporting.  Topics  Feat...","./images/zoomimage.jpg"],
["./expenditure.html","Expenditure","Overview  Achieve a high standard of transparency, plan and track your financials, payments to grantees and for bursaries. Create and refine ...","./images/zoomimage.jpg"],
["./faq.html","Frequently asked questions","Overview  Browse through the FAQ for answers to the most common questions asked by DevMan users. Questions are organised by category with lin...","./images/zoomimage.jpg"],
["./faqcommunication.html","Communication","Topics  This section answers questions related to the different types of communications often asked by DevMan users. DevMan provides the appr...","./images/zoomimage.jpg"],
["./faqemailsmsbroken.html","Troubleshooting - email / sms not working","Enter topic text here.","./images/zoomimage.jpg"],
["./faqgeneral.html","General","Topics  Topics related to system requirements, browsers and internet access.  What are the DevMan system requirements? DevMan is a cost-...","./images/zoomimage.jpg"],
["./faqsearch.html","Find and search","Topics  Questions on surfacing information from finding a single record to basic and advanced search.  Search as you type Search Search ...","./images/zoomimage.jpg"],
["./faqsupport.html","Support","Overview  Assist us to investigate and resolve your requests and complaints or errors correctly and as quickly as possible.  Your clear,...","./images/zoomimage.jpg"],
["./faqvieworgprj.html","How do I view my organisation&#39;s projects","Enter topic text here.","./images/zoomimage.jpg"],
["./fundraising2.html","Fundraising","Overview  Champion your worthy cause by using DevMan&#39;s intuitive fundraising and CRM solution. Automate routine activities, improve your repo...","./images/zoomimage.jpg"],
["./gettingstarted.html","Getting started","Overview  Learn how DevMan works, understand the key concepts and background information. Pick up useful tips and tricks, identify the key ar...","./images/zoomimage.jpg"],
["./grantmanagement.html","Grant management","Overview  Use this module for end-to-end management of your entire grantmaking cycle. Reduce data capture through use of customized online fo...","./images/zoomimage.jpg"],
["./importsandupdates.html","Imports and updates","Overview  Easily apply a series of changes to a group of records by using the bulk update feature. Updates can be made to people, organisatio...","./images/zoomimage.jpg"],
["./income.html","Income","Overview  Accurate financial records are the lifeblood of your operation. Use the finance module complete with all supporting processes to se...","./images/zoomimage.jpg"],
["./index.html","Introduction","Introduction to Devman3","./images/zoomimage.jpg"],
["./lead.html","Leads","Overview  Use this fundraising tool to track your prospect cultivation, from identification of potential donors through to contract approval ...","./images/zoomimage.jpg"],
["./linking.html","Linking","Link a person, organisation or project  Relationship links can be added and defined between people, organisations and projects.  These c...","./images/zoomimage.jpg"],
["./loggingin.html","Logging in","Overview  A strong login ensures that only authorised users gain access, preventing unauthorised access and potential breaches. Please see Se...","./images/zoomimage.jpg"],
["./mailshot.html","Mailshot","Overview  Mailshots are essential for effective email marketing as well as stakeholder engagement. Connect with your audience, send event inv...","./images/zoomimage.jpg"],
["./meeting.html","Meetings","Overview  Set up meetings and see which projects have been recommended and are on the agenda. Board members can also log in to view this. Add...","./images/zoomimage.jpg"],
["./mergecontacts.html","Merge contacts","Overview  If you have duplicate records of a person or organisation, these need to be merged to combine the history and linked records, such ...","./images/zoomimage.jpg"],
["./navigation.html","Navigation","Overview  To get started with DevMan, please view the step-by-step tutorials below. They outline the main elements you will encounter through...","./images/zoomimage.jpg"],
["./online-updates.html","Online updates","Overview  Contacts can review and update their own contact details directly in DevMan. DevMan provides two ways for contacts to safely update...","./images/zoomimage.jpg"],
["./onlineapplications.html","Online applications","Overview  Cut the administrative burden, take advantage of our online application tool.  Allow your bursary and grants applicants to app...","./images/zoomimage.jpg"],
["./onlinegiving.html","Online giving","Overview  Make giving effortless and simple with DevMan&#39;s integrated online giving portal. Offer donors a fast, easy and secure online giving...","./images/zoomimage.jpg"],
["./onlineresults.html","Online results","Overview  Employ your branded online results page to gather, track and monitor beneficiary submissions.  Topics  Features Bulk gene...","./images/zoomimage.jpg"],
["./organisations.html","Organisations","Overview  Contact details and a profile of your donor, prospect or grantee organisation can be captured here. See how to capture, save and ed...","./images/zoomimage.jpg"],
["./payments.html","Payments","Overview  Capture payments directly for once-off support, or handle via a fuller commitment cycle for grant funding.  Topics  Featu...","./images/zoomimage.jpg"],
["./people.html","People","Overview  This section will assist you to capture, save and edit your contacts&#39; details and profile. Links can be added to other profiles on ...","./images/zoomimage.jpg"],
["./pledges.html","Pledges","Overview   Topics","./images/zoomimage.jpg"],
["./project.html","Projects","Overview  Use this feature to track and report on applications for funding and approved projects. Manage project workflow, financials and doc...","./images/zoomimage.jpg"],
["./projects.html","Projects","Overview  Use this feature to track and report on fundraising causes – referred to as projects in DevMan. Manage fundraising workflow, donati...","./images/zoomimage.jpg"],
["./qualification.html","Qualification and results","Overview  Track your beneficiaries&#39; progress in achieving their qualification.  Use the dashboard for insights on key bursary management...","./images/zoomimage.jpg"],
["./quickguides.html","Product guides","Overview  We&#39;ve provided a number of guides explaining some of the more intricate features and processes on DevMan. These can be used for tra...","./images/zoomimage.jpg"],
["./sars.html","SARS","Overview  Achieve seamless tax compliance and donor data management.  Streamline s18A receipts and IT3(d) exports to SARS with our compr...","./images/zoomimage.jpg"],
["./sarsit3exports.html","SARS IT3 exports","Overview  Ensure accurate, efficient and compliant tax reporting. Use this feature to extract and export section 18A donor information as req...","./images/zoomimage.jpg"],
["./searching.html","Searching","Overview  Simple and advanced searching tools are available for most DevMan modules to assist with your reporting needs.  Topics  F...","./images/zoomimage.jpg"],
["./searchreport.html","Search &#38; report","Overview  DevMan&#39;s report and analytics platform provides rich search and reporting for all areas. Draw statistical high level summaries and ...","./images/zoomimage.jpg"],
["./section18areceipts.html","Section 18A receipts","Overview  Encourage donor giving by promptly providing any documentation they need for tax benefits available in their country.  Topics ...","./images/zoomimage.jpg"],
["./securityadvanced.html","Advanced","Overview  Secure your data, align DevMan user access with the security protocols in place at your organisation. These topics cover activities...","./images/zoomimage.jpg"],
["./subscription.html","Subscriptions","Overview  Centralise and streamline your communications with stakeholders, identify trends and develop targeted campaigns to generate growth....","./images/zoomimage.jpg"],
["./textmessage.html","SMS","Overview  Take advantage of SMS communication as an efficient way to engage stakeholders, complementing email communications and increasing e...","./images/zoomimage.jpg"],
["./whatsnew.html","What&#39;s new","New features in DevMan  DevMan self-service portal Say goodbye to the hassle of capturing SARS data. Donors can now update their own tax deta...","./images/zoomimage.jpg"],
["./workflow.html","Workflow","Overview  Combine DevMan milestones and workflow features to manage key steps, communications, reminders and reporting.  Topics  Fe...","./images/zoomimage.jpg"],
["./yearendrollover.html","Year-end rollover","Overview   Topics  Features Track year-end status of all beneficiaries: Completed - Rollover Completed - Graduated Terminated Manage rol...","./images/zoomimage.jpg"]];
