pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./accountingsystemintegration.htm","Accounting system integration","Accounting system integration Top Previous Next Overview Reduce errors and increase productivity with a single point of entry. DevMan integrates t...",""],
["./actionsdue.htm","Actions due","Actions due Top Overview By setting up reminders, you can keep track of which activities are due and which have been completed. Letter reminders a...",""],
["./activitiesinteraction.htm","Activities / Interactions","Activities / Interactions Top Overview As interactions are recorded on the system, you are notified in the Weekly activity section of the Home pag...",""],
["./aftertheevent.htm","After the event","After the event Top Previous Next Overview Enhance return on investment, engage with attendees and gather feedback via post-event surveys to drive...",""],
["./applicantsupport.htm","Applicant support","Applicant support Top Previous Next Overview If an applicant encounters difficulties when submitting their online application, check the topics be...",""],
["./attheevent.htm","At the event","At the event Top Previous Next Overview Build their confidence and delight your attendees with a seamless online registration experience. Manage r...",""],
["./beforetheevent.htm","Before the event","Before the event Top Previous Next Overview Plan the perfect event: kick off the planning process by addressing all components of the event. Stay ...",""],
["./budget.htm","Budget","Budget Top Previous Next Overview Align your budgets with expenditure, use this tool to load your budget before capturing any pledges or payments....",""],
["./bursary-profile.htm","Bursary profile","Bursary profile Top Previous Next Overview Initiate and solidify connections between students, sponsors and institutions. Provide comprehensive in...",""],
["./bursarymanagement.htm","Bursary management","Bursary management Top Previous Next Overview Transform your bursary management process with configurable, versatile workflow designed to streamli...",""],
["./businessunits.htm","Business units","Business units Top Previous Next Overview DevMan allows you to set up all your business units for an organisation in an easy to see hierarchy usin...",""],
["./commitmentsbudget.htm","Commitments","Commitments Top Previous Next Overview Improve spend forecasting accuracy and speed of data capture. This module is designed to streamline process...",""],
["./consent.htm","Consent","Consent Top Previous Next Overview Get your POPIA implementation plan off the ground, and painlessly achieve compliance by making practical use of...",""],
["./contract.htm","Contracts","Contracts Top Previous Next Overview Use this feature to manage all your contracts. Upload, store and organise your agreement records for easy acc...",""],
["./debitorders.htm","Debit orders","Debit orders Top Previous Next Overview Drive efficiency, streamline the monthly administration of your debit order donors by using DevMan’s integ...",""],
["./devcommunication.htm","Communication","Communication Top Previous Next Overview Engage and build rapport with your audience via email and SMS channels. Take advantage of workflow automa...",""],
["./devcontact.htm","Contacts","Contacts Top Previous Next Overview Use this feature to manage all your contacts. These may be linked to other contacts, organisations or projects...",""],
["./devdashboard.htm","Dashboards","Dashboards Top Previous Next Overview Transform data sets into analytical snapshots. View crucial information at a glance. Dashboards are accessib...",""],
["./devfinance.htm","Finance","Finance Top Previous Next Overview DevMan’s financial management component, designed to complement or integrate to your accounting systems is cruc...",""],
["./devmanfunction.htm","DevMan functions","DevMan functions Top Previous Next Overview Access key features you may need when working with DevMan. It is designed for clear navigation, to be ...",""],
["./devmanportal.htm","DevMan portal","DevMan portal Top Previous Next Overview Simplify your tax-related tasks. Empower donors to effortlessly update their own tax details. Topics Feat...",""],
["./devsecurity.htm","Security","Security Top Previous Next Overview Computer security is an important component of a successful organisation. Avoid complacency, control access to...",""],
["./documentmanagement.htm","Document management","Document management Top Previous Next Overview Reduce paper, and increase efficiency with the DevMan dossier (document) upload feature. Topics Fea...",""],
["./donationdepositprocess.htm","Donation deposit process","Donation deposit process Top Previous Next Overview Streamline the monthly administration and allocation of your donations received via direct ban...",""],
["./donations.htm","Donations","Donations Top Previous Next Overview Capture donations directly and if required, send a thank you letter to the donor . Topics Features Link donat...",""],
["./donorengagement.htm","Donor engagement","Donor engagement Top Previous Next Overview Nurture relationships with donors to improve engagement and monitor the various prospect stages. Evalu...",""],
["./donorprofile.htm","Donor profile","Donor profile Top Previous Next Overview The starting point in your cultivation of lifelong relationships with both organisations and individuals....",""],
["./email.htm","Email","Email Top Previous Next Overview Ensure your email campaigns are targeted and relevant, providing value to recipients to maintain their trust and ...",""],
["./emailsetup.htm","Email setup","Email setup Top Previous Next Overview Verify your email address and learn how to configure your sending domain. Topics Set up email The email add...",""],
["./eventmanagement.htm","Event management","Event management Top Previous Next Overview Create and manage memorable events, connect and engage with attendees to provide a more personalised e...",""],
["./excelintegratedreports.htm","Excel integrated reports","Excel integrated reports Top Previous Next Overview Effortlessly summarise, analyse and present data from DevMan directly to Excel for comprehensi...",""],
["./expenditure.htm","Expenditure","Expenditure Top Previous Next Overview Achieve a high standard of transparency, plan and track your financials, payments to grantees and for bursa...",""],
["./faq.htm","Frequently asked questions","Frequently asked questions Top Previous Next Overview Browse through the FAQ for answers to the most common questions asked by DevMan users. Quest...",""],
["./faqcommunication.htm","Communication","Communication Top Previous Next Topics This section answers questions related to the different types of communications often asked by DevMan users...",""],
["./faqemailsmsbroken.htm","Troubleshooting - email / sms not working","Enter topic text here. ",""],
["./faqgeneral.htm","General","General Top Previous Next Topics Topics related to system requirements, browsers and internet access. What are the DevMan system requirements? Dev...",""],
["./faqsearch.htm","Find and search","Find and search Top Previous Next Topics Questions on surfacing information from finding a single record to basic and advanced search. Search as y...",""],
["./faqsupport.htm","Support","Support Top Previous Next Overview Assist us to investigate and resolve your requests and complaints or errors correctly and as quickly as possibl...",""],
["./faqvieworgprj.htm","How do I view my organisation&#39;s projects","Enter topic text here. ",""],
["./fundraising2.htm","Fundraising","Fundraising Top Previous Next Overview Champion your worthy cause by using DevMan&#39;s intuitive fundraising and CRM solution. Automate routine activ...",""],
["./gettingstarted.htm","Getting started","Getting started Top Previous Next Overview Learn how DevMan works, understand the key concepts and background information. Pick up useful tips and...",""],
["./grantmanagement.htm","Grant management","Grant management Top Previous Next Overview Use this module for end-to-end management of your entire grantmaking cycle. Reduce data capture throug...",""],
["./importsandupdates.htm","Imports and updates","Imports and updates Top Previous Next Overview Easily apply a series of changes to a group of records by using the bulk update feature. Updates ca...",""],
["./income.htm","Income","Income Top Previous Next Overview Accurate financial records are the lifeblood of your operation. Use the finance module complete with all support...",""],
["./lead.htm","Leads","Leads Top Previous Next Overview Use this fundraising tool to track your prospect cultivation, from identification of potential donors through to ...",""],
["./linking.htm","Linking","Linking Top Previous Next Link a person, organisation or project Relationship links can be added and defined between people, organisations and pro...",""],
["./loggingin.htm","Logging in","Logging in Top Previous Next Overview A strong login ensures that only authorised users gain access, preventing unauthorised access and potential ...",""],
["./mailshot.htm","Mailshot","Mailshot Top Previous Next Overview Mailshots are essential for effective email marketing as well as stakeholder engagement. Connect with your aud...",""],
["./meeting.htm","Meetings","Meetings Top Previous Next Overview Set up meetings and see which projects have been recommended and are on the agenda. Board members can also log...",""],
["./mergecontacts.htm","Merge contacts","Merge contacts Top Previous Next Overview If you have duplicate records of a person or organisation, these need to be merged to combine the histor...",""],
["./navigation.htm","Navigation","Navigation Top Previous Next Overview To get started with DevMan, please view the step-by-step tutorials below. They outline the main elements you...",""],
["./online-updates.htm","Online updates","Online updates Top Previous Next Overview Contacts can review and update their own contact details directly in DevMan. DevMan provides two ways fo...",""],
["./onlineapplications.htm","Online applications","Online applications Top Previous Next Overview Cut the administrative burden, take advantage of our online application tool. Allow your bursary an...",""],
["./onlinegiving.htm","Online giving","Online giving Top Previous Next Overview Make giving effortless and simple with DevMan&#39;s integrated online giving portal. Offer donors a fast, eas...",""],
["./onlineresults.htm","Online results","Online results Top Previous Next Overview Employ your branded online results page to gather, track and monitor beneficiary submissions. Topics Fea...",""],
["./organisations.htm","Organisations","Organisations Top Previous Next Overview Contact details and a profile of your donor, prospect or grantee organisation can be captured here. See h...",""],
["./payments.htm","Payments","Payments Top Previous Next Overview Capture payments directly for once-off support, or handle via a fuller commitment cycle for grant funding. Top...",""],
["./people.htm","People","People Top Previous Next Overview This section will assist you to capture, save and edit your contacts&#39; details and profile. Links can be added to...",""],
["./pledges.htm","Pledges","Pledges Top Previous Next Overview Topics ",""],
["./project.htm","Projects","Projects Top Previous Next Overview Use this feature to track and report on applications for funding and approved projects. Manage project workflo...",""],
["./projects.htm","Projects","Projects Top Previous Next Overview Use this feature to track and report on fundraising causes – referred to as projects in DevMan. Manage fundrai...",""],
["./qualification.htm","Qualification and results","Qualification and results Top Previous Next Overview Track your beneficiaries&#39; progress in achieving their qualification. Use the dashboard for in...",""],
["./quickguides.htm","Product guides","Product guides Top Previous Next Overview We&#39;ve provided a number of guides explaining some of the more intricate features and processes on DevMan...",""],
["./sars.htm","SARS","SARS Top Previous Next Overview Achieve seamless tax compliance and donor data management. Streamline s18A receipts and IT3(d) exports to SARS wit...",""],
["./sarsit3exports.htm","SARS IT3 exports","SARS IT3 exports Top Previous Next Overview Ensure accurate, efficient and compliant tax reporting. Use this feature to extract and export section...",""],
["./searching.htm","Searching","Searching Top Previous Next Overview Simple and advanced searching tools are available for most DevMan modules to assist with your reporting needs...",""],
["./searchreport.htm","Search &#38; report","Search &#38; report Top Previous Next Overview DevMan&#39;s report and analytics platform provides rich search and reporting for all areas. Draw statistic...",""],
["./section18areceipts.htm","Section 18A receipts","Section 18A receipts Top Previous Next Overview Encourage donor giving by promptly providing any documentation they need for tax benefits availabl...",""],
["./securityadvanced.htm","Advanced","Advanced Top Previous Next Overview Secure your data, align DevMan user access with the security protocols in place at your organisation. These to...",""],
["./subscription.htm","Subscriptions","Subscriptions Top Previous Next Overview Centralise and streamline your communications with stakeholders, identify trends and develop targeted cam...",""],
["./textmessage.htm","SMS","SMS Top Previous Next Overview Take advantage of SMS communication as an efficient way to engage stakeholders, complementing email communications ...",""],
["./welcometodevman.htm","Introduction","Introduction Top Next Welcome If you are new to DevMan, please consider our Getting started section below. You will find helpful resources which y...",""],
["./whatsnew.htm","What&#39;s new","What&#39;s new? Top Previous Next New features in DevMan DevMan self-service portal Say goodbye to the hassle of capturing SARS data. Donors can now u...",""],
["./workflow.htm","Workflow","Workflow Top Previous Overview Combine DevMan milestones and workflow features to manage key steps, communications, reminders and reporting. Topic...",""],
["./yearendrollover.htm","Year-end rollover","Year-end rollover Top Previous Next Overview Topics Features Track year-end status of all beneficiaries: oCompleted - Rollover oCompleted - Gradua...",""]];
